services:
  overseerr:
    image: ghcr.io/tw1zt3d2four7/overseer/lidarr:v0.1.0_dev_lid_alpha
    container_name: overseerr
    pull_policy: always
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/app/config
      - /mnt:/mnt
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    
